import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationContextProvider } from "@/context/navigation-context";
import Sidebar from "@/sections/navbar/Sidebar";
import Modal from "@/components/modal/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavigationContextProvider>
          <Sidebar />
          <main>
            {children}
          </main>
          <Modal />
        </NavigationContextProvider>
      </body>
    </html>
  );
}
